trigger:
  branches:
    exclude:
    - main

pool:
  vmImage: ubuntu-latest

variables:
      tafSolutionPath: '$(Build.SourcesDirectory)/report-portal-tests/ReportPortal.Tests'

steps:
  - task: UseDotNet@2
    inputs:
      version: '6.0.x'
      includePreviewVersions: true

  - task: NuGetToolInstaller@1

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '$(tafSolutionPath)/*.sln'
    displayName: 'Nuget restore'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(tafSolutionPath)/*.sln'
      arguments: '-c Release --no-restore'
      workingDirectory: '$(tafSolutionPath)'
    displayName: 'Build TAF solution'
